const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TS_PATH = path.join(ROOT, "study_source", "opencc", "TSCharacters.txt");
const LIST_PATH = path.join(ROOT, "study_source", "general-standard-characters", "1-8105.txt");
const HZ_DATA_DIR = path.join(ROOT, "study_source", "hanzi-writer-data", "package");
const OUT_PATH = path.join(ROOT, "app", "data", "characters.js");

function readUtf8(file) {
  return fs.readFileSync(file, "utf8").replace(/^\uFEFF/, "");
}

function parseOfficialList(text) {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const order = new Map();
  lines.forEach((ch, i) => order.set(ch, i));
  return { chars: lines, order };
}

function parseTSCharacters(text) {
  const pairs = [];
  const lines = text.split(/\r?\n/);
  for (const rawLine of lines) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const idx = line.indexOf("\t");
    if (idx === -1) continue;
    const traditional = line.slice(0, idx);
    const values = line.slice(idx + 1).trim().split(/\s+/).filter(Boolean);
    if (!traditional || values.length === 0) continue;
    const simplified = values[0];
    if (!simplified || simplified === traditional) continue;
    pairs.push({ traditional, simplified, candidates: values });
  }
  return pairs;
}

function hasStrokeData(ch) {
  return fs.existsSync(path.join(HZ_DATA_DIR, `${ch}.json`));
}

function readStrokeData(ch) {
  const file = path.join(HZ_DATA_DIR, `${ch}.json`);
  if (!fs.existsSync(file)) return null;
  return JSON.parse(fs.readFileSync(file, "utf8"));
}

function main() {
  const listText = readUtf8(LIST_PATH);
  const { chars, order } = parseOfficialList(listText);
  const tsText = readUtf8(TS_PATH);
  const rawPairs = parseTSCharacters(tsText);

  const valid = [];
  const missingTraditional = new Set();
  const missingSimplified = new Set();
  for (const p of rawPairs) {
    if (!order.has(p.simplified)) continue;
    if (!hasStrokeData(p.traditional)) {
      missingTraditional.add(p.traditional);
      continue;
    }
    if (!hasStrokeData(p.simplified)) {
      missingSimplified.add(p.simplified);
      continue;
    }
    valid.push(p);
  }

  valid.sort((a, b) => order.get(a.simplified) - order.get(b.simplified));

  const strokes = {};
  const pairsOut = valid.map((p) => {
    if (!strokes[p.traditional]) strokes[p.traditional] = readStrokeData(p.traditional);
    if (!strokes[p.simplified]) strokes[p.simplified] = readStrokeData(p.simplified);
    return {
      t: p.traditional,
      s: p.simplified,
      // first 4 candidate simplified forms can power "which one is correct" distractor options
      alt: p.candidates.slice(0, 4),
    };
  });

  const out = {
    generatedAt: new Date().toISOString(),
    sources: {
      traditionalSimplified: "OpenCC TSCharacters.txt (Apache-2.0), https://github.com/BYVoid/OpenCC",
      commonList: "《通用规范汉字表》8105字顺序表, https://github.com/iDvel/The-Table-of-General-Standard-Chinese-Characters",
      strokes: "HanziWriter Data 2.0.1 (derived from Make Me a Hanzi), ARPHICPL license",
    },
    counts: {
      officialChars: chars.length,
      rawMappedPairs: rawPairs.length,
      usablePairs: pairsOut.length,
      missingTraditionalStroke: missingTraditional.size,
      missingSimplifiedStroke: missingSimplified.size,
    },
    pairs: pairsOut,
    strokes,
  };

  const js = `// Generated by tools/build-data.js from professional open data.\n// Do not edit by hand.\nwindow.LEARNING_DATA = ${JSON.stringify(out)};\n`;
  fs.writeFileSync(OUT_PATH, js, "utf8");

  console.log(JSON.stringify(out.counts, null, 2));
  console.log("Written:", OUT_PATH, `${(fs.statSync(OUT_PATH).size / 1024 / 1024).toFixed(2)} MB`);
}

main();
